import { DataSource } from "typeorm";
import { KitHistory } from "../database/entities/kit-history.entity";

const WIKIMEDIA = (filename: string) =>
  `https://upload.wikimedia.org/wikipedia/commons/thumb/${filename}`;

export const KITS_DATA: Partial<KitHistory>[] = [
  // === 1910s-1920s: Fundação ===
  { yearStart: 1910, yearEnd: 1918, type: "home", manufacturer: "Artesanal", eraLabel: "Fundação", title: "Uniforme Fundação 1910", description: "Uniforme original do clube fundado em 1/9/1910 por operários da Fábrica de Tecidos Santana. Camisa listrada vertical preta e branca, calção preto. Cores adotadas em homenagem ao Sport Club Corinthian (inglês), que visitou São Paulo naquele ano.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Corinthians_1910.png/120px-Corinthians_1910.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 1 },
  { yearStart: 1919, yearEnd: 1929, type: "home", manufacturer: "Artesanal", eraLabel: "Anos 1910-20", title: "Uniforme Titular 1919", description: "Consolidação das cores preto e branco. Camisa branca com listras verticais pretas, calção branco. Meias pretas e brancas.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Corinthians_1919.png/120px-Corinthians_1919.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 2 },

  // === 1930s ===
  { yearStart: 1930, yearEnd: 1939, type: "home", manufacturer: "Artesanal", eraLabel: "Anos 1930", title: "Uniforme Titular 1930", description: "Design refinado com listras mais largas. O Corinthians já era um dos clubes mais populares do Brasil nesta época.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Corinthians_1930.png/120px-Corinthians_1930.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 3 },
  { yearStart: 1930, yearEnd: 1939, type: "away", manufacturer: "Artesanal", eraLabel: "Anos 1930", title: "Uniforme Reserva 1930", description: "Camisa preta lisa para jogos como visitante. Calção branco.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Corinthians_1930_away.png/120px-Corinthians_1930_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 4 },

  // === 1940s ===
  { yearStart: 1940, yearEnd: 1948, type: "home", manufacturer: "Artesanal", eraLabel: "Anos 1940", title: "Uniforme Titular 1940", description: "Período dourado do Corinthians. Camisa branca com listras verticais pretas estreitas. Time campeão paulista consecutivo.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Corinthians_1940.png/120px-Corinthians_1940.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 5 },
  { yearStart: 1949, yearEnd: 1949, type: "special", manufacturer: "Artesanal", eraLabel: "Homenagem Torino", title: "Uniforme Homenagem Torino 1949", description: "Uniforme especial em homenagem ao Grande Torino, vítima do desastre aéreo de Superga em 4/5/1949. O Corinthians tinha amizade com o clube italiano e adotou temporariamente a cor vinho/granata do Torino.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Corinthians_1949_torino.png/120px-Corinthians_1949_torino.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 6 },

  // === 1950s ===
  { yearStart: 1950, yearEnd: 1951, type: "home", manufacturer: "Artesanal", eraLabel: "Anos 1950", title: "Uniforme Titular 1950", description: "Camisa branca com listras pretas. Era de ouro do futebol paulista.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Corinthians_1950.png/120px-Corinthians_1950.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 7 },
  { yearStart: 1952, yearEnd: 1952, type: "home", manufacturer: "Ceppo", eraLabel: "Anos 1950", title: "Uniforme Ceppo 1952", description: "Primeiro uniforme fabricado pela Ceppo. Manteve o design clássico de listras.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Corinthians_1952.png/120px-Corinthians_1952.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 8 },
  { yearStart: 1955, yearEnd: 1955, type: "home", manufacturer: "Athleta", eraLabel: "Anos 1950", title: "Uniforme Athleta 1955", description: "Uniforme fabricado pela Athleta. Design com listras verticais tradicionais.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Corinthians_1955.png/120px-Corinthians_1955.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 9 },
  { yearStart: 1956, yearEnd: 1959, type: "home", manufacturer: "Artesanal", eraLabel: "Anos 1950", title: "Uniforme Titular 1956", description: "Retorno ao uniforme artesanal. Listras verticais pretas e brancas clássicas.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Corinthians_1956.png/120px-Corinthians_1956.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 10 },

  // === 1960s ===
  { yearStart: 1960, yearEnd: 1969, type: "home", manufacturer: "Artesanal", eraLabel: "Anos 1960", title: "Uniforme Titular 1960", description: "Decade de consolidação. O Corinthians manteve seu design tradicional de listras verticais.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Corinthians_1960.png/120px-Corinthians_1960.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 11 },
  { yearStart: 1960, yearEnd: 1969, type: "away", manufacturer: "Artesanal", eraLabel: "Anos 1960", title: "Uniforme Reserva 1960", description: "Camisa preta para jogos fora. Design simples e clássico.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Corinthians_1960_away.png/120px-Corinthians_1960_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 12 },

  // === 1970s ===
  { yearStart: 1970, yearEnd: 1976, type: "home", manufacturer: "Artesanal", eraLabel: "Anos 1970", title: "Uniforme Titular 1970", description: "Início dos anos 70 com design moderno. Listras pretas e brancas em camisa com gola V.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Corinthians_1970.png/120px-Corinthians_1970.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 13 },
  { yearStart: 1977, yearEnd: 1979, type: "home", manufacturer: "Penalty", eraLabel: "Era Penalty", title: "Uniforme Penalty 1977", description: "Primeiro contrato com a Penalty, marca esportiva brasileira. Início da era de uniformes industrializados.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Corinthians_1977.png/120px-Corinthians_1977.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 14 },

  // === 1980s: Era Topper + Democracia Corinthiana ===
  { yearStart: 1980, yearEnd: 1982, type: "home", manufacturer: "Topper", eraLabel: "Era Topper", title: "Uniforme Topper 1980", description: "Início da parceria com a Topper. Camisa listrada com novo corte moderno.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Corinthians_1980.png/120px-Corinthians_1980.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 15 },
  { yearStart: 1982, yearEnd: 1984, type: "home", manufacturer: "Topper", eraLabel: "Democracia Corinthiana", title: "Uniforme Cofap 1982", description: "Período da Democracia Corinthiana (1982-84), movimento único no futebol onde jogadores e funcionários tinham voto igualitário. Primeiro grande patrocínio: Cofap. Campeonato Brasileiro 1982.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Corinthians_1982.png/120px-Corinthians_1982.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 16 },
  { yearStart: 1983, yearEnd: 1983, type: "home", manufacturer: "Topper", eraLabel: "Democracia Corinthiana", title: "Uniforme Cofap 1983", description: "Campeonato Brasileiro 1983. Mesma camisa icônica do movimento democrático, com patrocínio Cofap.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Corinthians_1983.png/120px-Corinthians_1983.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 17 },
  { yearStart: 1985, yearEnd: 1989, type: "home", manufacturer: "Topper", eraLabel: "Era Topper", title: "Uniforme Topper 1985", description: "Continuidade com Topper. Design moderno com listras mais largas.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Corinthians_1985.png/120px-Corinthians_1985.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 18 },
  { yearStart: 1985, yearEnd: 1989, type: "away", manufacturer: "Topper", eraLabel: "Era Topper", title: "Uniforme Reserva Topper 1985", description: "Camisa preta como reserva da Topper.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Corinthians_1985_away.png/120px-Corinthians_1985_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 19 },

  // === 1990s: Era Finta e Penalty ===
  { yearStart: 1990, yearEnd: 1994, type: "home", manufacturer: "Finta", eraLabel: "Era Finta", title: "Uniforme Finta 1990", description: "Parceria com a marca portuguesa Finta. Design inovador com elementos gráficos modernos.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Corinthians_1990.png/120px-Corinthians_1990.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 20 },
  { yearStart: 1990, yearEnd: 1994, type: "away", manufacturer: "Finta", eraLabel: "Era Finta", title: "Uniforme Reserva Finta 1990", description: "Camisa preta da Finta para jogos como visitante.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Corinthians_1990_away.png/120px-Corinthians_1990_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 21 },
  { yearStart: 1995, yearEnd: 1998, type: "home", manufacturer: "Penalty", eraLabel: "Era Penalty II", title: "Uniforme Penalty 1995", description: "Retorno à Penalty. Novo design com listras mais definidas e gola redonda.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Corinthians_1995.png/120px-Corinthians_1995.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 22 },
  { yearStart: 1997, yearEnd: 1997, type: "home", manufacturer: "Penalty", eraLabel: "Era Penalty II", title: "Uniforme Penalty Centenário 1997", description: "Uniforme especial para as comemorações. Detalhes em dourado celebrando os 87 anos do clube.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Corinthians_1997.png/120px-Corinthians_1997.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 23 },

  // === 1999-2002: Era Topper II ===
  { yearStart: 1999, yearEnd: 2002, type: "home", manufacturer: "Topper", eraLabel: "Era Topper II", title: "Uniforme Topper 1999", description: "Retorno à Topper para nova fase. Camisa com novo corte e listras refinadas.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Corinthians_1999.png/120px-Corinthians_1999.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 24 },
  { yearStart: 2000, yearEnd: 2000, type: "special", manufacturer: "Topper", eraLabel: "Mundial FIFA 2000", title: "Uniforme Mundial FIFA 2000", description: "Uniforme usado no Mundial de Clubes da FIFA no Brasil. O Corinthians venceu o torneio inédito, sendo o primeiro campeão mundial de clubes da história. Detalhe especial dourado.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Corinthians_2000_mundial.png/120px-Corinthians_2000_mundial.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 25 },
  { yearStart: 2001, yearEnd: 2001, type: "home", manufacturer: "Topper", eraLabel: "Era Topper II", title: "Uniforme Topper 2001", description: "Camisa especial com detalhes em azul. Período de adaptação ao novo milênio.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Corinthians_2001.png/120px-Corinthians_2001.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 26 },

  // === 2003+: Era Nike ===
  { yearStart: 2003, yearEnd: 2003, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2003 — Estreia", description: "Início da parceria com a Nike, que dura até hoje. Primeiro uniforme Nike: listras verticais pretas e brancas com tecnologia Dri-FIT. Patrocínio Siemens Mobile.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Corinthians_2003.png/120px-Corinthians_2003.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 27 },
  { yearStart: 2003, yearEnd: 2003, type: "away", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Reserva Nike 2003", description: "Primeiro uniforme reserva Nike: camisa preta com listras brancas laterais.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Corinthians_2003_away.png/120px-Corinthians_2003_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 28 },
  { yearStart: 2004, yearEnd: 2005, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2004", description: "Segundo ano com Nike. Refinamento do design com novas tecnologias de tecido.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Corinthians_2004.png/120px-Corinthians_2004.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 29 },
  { yearStart: 2006, yearEnd: 2007, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2006", description: "Design moderno com listras duplas. Ano de retorno à Série A após rebaixamento.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Corinthians_2006.png/120px-Corinthians_2006.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 30 },
  { yearStart: 2008, yearEnd: 2008, type: "third", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Roxo 2008", description: "Icônico terceiro uniforme roxo que se tornou símbolo do estilo ousado da Nike. Um dos uniformes mais lembrados e queridos pela Fiel Torcida.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Corinthians_2008_third.png/120px-Corinthians_2008_third.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 31 },
  { yearStart: 2008, yearEnd: 2009, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2008", description: "Listras verticais clássicas com novo corte esportivo. Patrocínio Fiat.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Corinthians_2008.png/120px-Corinthians_2008.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 32 },
  { yearStart: 2010, yearEnd: 2010, type: "special", manufacturer: "Nike", eraLabel: "Centenário 2010", title: "Uniforme Centenário 2010", description: "Uniforme especial para o Centenário do Corinthians (1910-2010). Detalhes dourados em homenagem aos 100 anos do Timão. Um dos uniformes mais especiais da história do clube.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Corinthians_2010_centenary.png/120px-Corinthians_2010_centenary.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 33 },
  { yearStart: 2010, yearEnd: 2011, type: "home", manufacturer: "Nike", eraLabel: "Centenário 2010", title: "Uniforme Titular 2010", description: "Camisa do centenário. Listras verticais com logo especial comemorativo.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Corinthians_2010.png/120px-Corinthians_2010.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 34 },
  { yearStart: 2012, yearEnd: 2012, type: "home", manufacturer: "Nike", eraLabel: "Mundial 2012", title: "Uniforme Mundial de Clubes 2012", description: "Uniforme usado na conquista do Mundial de Clubes FIFA no Japão. Vitória sobre o Chelsea na final. Um dos momentos mais gloriosos da história do Corinthians.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Corinthians_2012_mundial.png/120px-Corinthians_2012_mundial.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 35 },
  { yearStart: 2012, yearEnd: 2012, type: "away", manufacturer: "Nike", eraLabel: "Mundial 2012", title: "Uniforme Reserva 2012", description: "Camisa preta usada na Copa Libertadores 2012, vencida pelo Timão.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Corinthians_2012_away.png/120px-Corinthians_2012_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 36 },
  { yearStart: 2013, yearEnd: 2014, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2013", description: "Pós-conquistas mundiais. Design refinado com nova tecnologia Vapor.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Corinthians_2013.png/120px-Corinthians_2013.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 37 },
  { yearStart: 2014, yearEnd: 2014, type: "third", manufacturer: "Nike", eraLabel: "Era Nike", title: "Terceiro Uniforme Bordô 2014", description: "Terceiro uniforme especial na cor bordô. Referência ao uniforme de homenagem ao Torino de 1949.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Corinthians_2014_third.png/120px-Corinthians_2014_third.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 38 },
  { yearStart: 2015, yearEnd: 2016, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2015", description: "Novo template Nike com listras mais largas e tecido Aeroswift.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Corinthians_2015.png/120px-Corinthians_2015.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 39 },
  { yearStart: 2015, yearEnd: 2016, type: "away", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Reserva Preto 2015", description: "Camisa preta com detalhes brancos. Design minimalista.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Corinthians_2015_away.png/120px-Corinthians_2015_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 40 },
  { yearStart: 2017, yearEnd: 2018, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2017", description: "Listras pretas e brancas com novo corte slim fit. Temporada do Campeonato Brasileiro.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Corinthians_2017.png/120px-Corinthians_2017.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 41 },
  { yearStart: 2017, yearEnd: 2018, type: "away", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Reserva 2017", description: "Terceiro uniforme cinza escuro com detalhes pretos. Muito bem recebido pela torcida.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Corinthians_2017_away.png/120px-Corinthians_2017_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 42 },
  { yearStart: 2019, yearEnd: 2020, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2019", description: "Design moderno com listras diagonais sutis. Novo template global Nike.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Corinthians_2019.png/120px-Corinthians_2019.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 43 },
  { yearStart: 2019, yearEnd: 2020, type: "away", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Reserva Preto 2019", description: "Camisa preta com logo branco. Design clean e elegante.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Corinthians_2019_away.png/120px-Corinthians_2019_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 44 },
  { yearStart: 2021, yearEnd: 2022, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2021", description: "Listras icônicas com tecnologia Nike Dri-FIT ADV. Uniforme das campanhas de Libertadores.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Corinthians_2021.png/120px-Corinthians_2021.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 45 },
  { yearStart: 2021, yearEnd: 2022, type: "away", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Reserva Verde 2021", description: "Uniforme reserva verde-limão. Homenagem às cores do Corinthians em 1921.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Corinthians_2021_away.png/120px-Corinthians_2021_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 46 },
  { yearStart: 2022, yearEnd: 2022, type: "special", manufacturer: "Nike", eraLabel: "Democracia Corinthiana", title: "Uniforme Democracia Corinthiana 2022", description: "Edição especial comemorando 40 anos da Democracia Corinthiana (1982-2022). Homenagem ao movimento que influenciou gestões democráticas no esporte mundial.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Corinthians_2022_democracia.png/120px-Corinthians_2022_democracia.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 47 },
  { yearStart: 2023, yearEnd: 2024, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2023", description: "Design contemporâneo mantendo as listras tradicionais. Tecnologia mais sustentável com uso de materiais reciclados.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Corinthians_2023.png/120px-Corinthians_2023.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 48 },
  { yearStart: 2023, yearEnd: 2024, type: "away", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Reserva Dourado 2023", description: "Uniforme reserva com toque dourado, celebrando conquistas históricas. Muito bem recebido pela Fiel.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Corinthians_2023_away.png/120px-Corinthians_2023_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 49 },
  { yearStart: 2025, yearEnd: 2026, type: "home", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Nike 2025", description: "Mais recente uniforme titular do Corinthians. Listras verticais clássicas com nova tecnologia Nike. Acompanhe em fielriopardo.com.br novos lançamentos.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Corinthians_2025.png/120px-Corinthians_2025.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 50 },
  { yearStart: 2025, yearEnd: 2026, type: "away", manufacturer: "Nike", eraLabel: "Era Nike", title: "Uniforme Reserva 2025", description: "Uniforme reserva preto 2025 com design moderno e listras brancas.", imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Corinthians_2025_away.png/120px-Corinthians_2025_away.png", sourceCredit: "Wikipedia CC-BY-SA", displayOrder: 51 },
];

export async function seedKits(dataSource: DataSource) {
  const repo = dataSource.getRepository(KitHistory);
  const existing = await repo.count();
  if (existing > 0) {
    console.log(`Kit history already has ${existing} records, skipping seed.`);
    return;
  }
  await repo.save(KITS_DATA.map((d) => repo.create(d)));
  console.log(`Seeded ${KITS_DATA.length} kit history records.`);
}
